swagger:
  outputDirectory: ./dist
  entryFile: 
    - "./src/controller/*"
  outputFormat: OpenApi_3
  name: USPO
  description: Universal Report System Server
  license: MIT
  produces: [application/json]
  version: 1.0.0
  ignore:
    - "**/node_modules/**"